logging:
  level:
    sql: info
    root: info
    web: debug
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/user_address_db
    username: test_user
    password: test_password
  mail:
    host: smtp.ukr.net
    port: 2525
    username: user3101bro@ukr.net
    password: vevUF38o4V0t59Kx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true