logging:
  level:
    sql: info
    root: info
    web: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5438/user_address_db
    username: test_user
    password: test_password
  mail:
    host: smtp.gmail.com
    port: 587
    username: yefremov.alexandr.guru@gmail.com
    password: cqwmzxiulmlmhqjh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
