create table if not exists user_profile
(
    id            bigint generated by default as identity not null
        constraint user_profile_pk primary key,
    version       bigint    default 0                     not null,
    created_date  timestamp default now()                 not null,
    modified_date timestamp default now()                 not null,
    first_name    varchar(100)                            not null,
    last_name     varchar(100)                            not null,
    patronymic    varchar(100),
    email         varchar(255)                            not null,
    constraint user_profile_email_not_unique unique (email),
    constraint user_profile_full_name_not_unique unique(first_name,last_name)
);
create index if not exists user_profile_patronymic_index on user_profile(patronymic);
