create table if not exists address
(
    id            bigint generated by default as identity not null
        constraint address_pk primary key,
    version       bigint    default 0                     not null,
    created_date  timestamp default now()                 not null,
    modified_date timestamp default now()                 not null,
    city varchar(30) not null ,
    street varchar(50) not null ,
    house varchar(10) not null ,
    flat_number varchar(10),
    user_id bigint not null constraint address_user_fk references  address,
    country_id bigint not null constraint address_country_fk references country
);
create index address_city_index on address(city);
create index address_country_index on address(country_id);
create index address_user_index on address(user_id);